### PR TITLE
feature:#6 duplicating a document added

### PR DESCRIPTION
**Pull request by Dharmik3**
feature #6 Duplicating a document

- Both places the duplication option added
- Created the one API function for copy
- onHover cursor effect added

Snapshot:

https://github.com/user-attachments/assets/81239a03-db85-47a4-930a-28d3f73ef0fc

### CODE REVIEW

**Comment by Nick-h4ck3r** [comment]
Looks good @Dharmik3! Just update the `auth.config.js` with the original domain.

**Comment by Nick-h4ck3r** [comment]
Additionally, a shorthand for creating a duplicate will be great, like `ctrl+d` or something.

**Comment by Dharmik3** [comment]
Hey @Nick-h4ck3r I have replaced the auth.config.js url

**Comment by Nick-h4ck3r** [comment]
Great job, @Dharmik3! Congratulations on your first contribution to Quickflow.

Looking forward to more contributions from you! 👏🏻

**Pull request merged**
